version: '3.4'

services:
  app:
    image: 'app'
    container_name: 'app'
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    networks:
      - backend

  frontend:
    image: 'frontend'
    container_name: 'frontend'
    build:
      context: frontend
      dockerfile: Dockerfile
    depends_on:
      - app
    ports:
      - '80:80'
    networks:
      - backend

networks:
  backend:
    driver: bridge